### PR TITLE
Simpler list processing

### PR DESCRIPTION
**Pull request by frougon**
Proposal for easier to read (and hopefully maintain!) list processing, as discussed in the comments [at topanswers.xyz](https://topanswers.xyz/tex?q=2030).

### CODE REVIEW

**Comment by frougon** [comment]
Indeed, many things are loaded, and in this case, the speed difference between both options should be very, _very_ small. :)

**Comment by frougon** [comment]
Another thing: I (almost) kept the old name `\tikzlings_iteratesearch:N` in tikzlings-addons.sty, but that should rather be `\__tikzlings_iteratesearch:` because it's clearly a private func.

If you tell me how you want to format `\c__tikzlings_clist` (with spaces: yes, got it, but also with the columns aligned?), I can rebase and file a new PR replacing this one, in order to have clean diffs (i.e., I would modify commit a8f142fc4d604f). Or replace the commits in this PR if this is possible (I'm used to the SourceForge workflow, not much to the GitHub one...).

**Comment by samcarter** [comment]
I'd say spaces yes, aligned columns no 

Thank you!

**Comment by samcarter** [comment]
(about the technicalities: do whatever is easiest for you. A new PR or just adding one more commit is all fine for me )

**Comment by frougon** [comment]
I've force-pushed the commits to this request. I've changed the code in tikzlings-addons.sty because we **don't** want a trailing comma at the end of the `.search also` argument here (this would make the search look in the root, as we saw). So, that's why I use `\seq_use:Nn` in

```
\seq_clear:N \l_tmpa_seq

\clist_map_inline:Nn \g__tikzlings_names_clist
  {
    \seq_put_right:Nn \l_tmpa_seq { /#1 }
  }

% Comma list such as '/anteater,/bat,/bear,...,/wolf' for use with the
% '.search also' handler
\clist_const:Nx \c__tikzlings_search_paths_clist
  {
    \seq_use:Nn \l_tmpa_seq { , }
  }
```

This contrasts with `\tikzset{...}` where empty items (e.g. from trailing commas) don't matter!

**Comment by samcarter** [comment]
@frougon  Thanks for catching this!

I've tested with all files in my collection and it seems to work perfectly fine. I'll sort out a new release version tomorrow or the day after

**Comment by frougon** [comment]
Thanks, you've been quick to incorporate the new vars and document the `pic` stuff!

Good night! :-)

**Comment by samcarter** [comment]
The lookup of all animals keys from thing is just to avoid errors if I pass on all options from say `\cat[hat,whiskers]`  to `\thing[#1]` which is called inside the cat macro. I previously tried to only pass on "unconsumed" keys that were not specifically for the animal, but then I ran into problems that thing wouldn't know about the normal tikz and pgf keys...

This way I can just dump all keys at thing and they won't hurt.

**Comment by samcarter** [comment]
... I should probably do something similar for the random `\tikzling` to avoid them moaning about unknown keys...

**Comment by frougon** [comment]
Ah okay, I see the `\thing[#1]` in animal pictures. The `pgfkeys` doc has a section on key filtering that might have helped, but I've never used this stuff.

Regarding your last comment, I believe [this](https://github.com/samcarter/tikzlings/compare/main...frougon:search-also-handler-for-random-tikzling) should be close to what you want. I tested it with:

```
\documentclass{standalone}
\usepackage{tikzlings}

\begin{document}
\begin{tikzpicture}
  \filldraw[blue!40] (-2,-2) rectangle (2,3);
  \tikzling[hat=red, fill opacity=0.2]
\end{tikzpicture}
\end{document}
```

The search in /tikz and /pgf allows the `fill opacity` not to trigger any error, however I don't see its effect. Maybe it is overridden by the “animal code”? Do you have an example where keys from /tikz or /pgf would make a difference here?

**Comment by frougon** [comment]
Oops, sorry: while I was focused on the details this afternoon, I forgot the essential part... I believe you wanted to be able to say for instance:

```
\tikzling[hat=red, whiskers=green]
```

in such a way that it:

- puts green whiskers if applicable to the randomly chosen tikzling;
- doesn't raise any error otherwise.

This is done [here](https://github.com/samcarter/tikzlings/compare/main...frougon:search-also-handler-for-random-tikzling) (commit 4a409491368846ffb465927337ddaef4983079d which I force-pushed to my `search-also-handler-for-random-tikzling` branch; can file a PR if you wish).

**Comment by frougon** [comment]
I force-pushed again to my [search-also-handler-for-random-tikzling](https://github.com/frougon/tikzlings/tree/search-also-handler-for-random-tikzling) branch (commit e54f6cc78b32bbb6f77b3f7229c3c8e425e72eec) because this

```
\use:c {#1} [{#2}]
```

is better than this:

```
\use:c {#1} [#2]
```

in case `#2` contains square brackets.

**Comment by samcarter** [comment]
@frougon  Oh, this seems to work great! Please do make a PR! 

Thanks a lot for looking into this!

**Comment by frougon** [comment]
PR filed: https://github.com/samcarter/tikzlings/pull/30 :-)

**Pull request merged**
